services:

  # ─── INFRAESTRUTURA ───────────────────────────────────────

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Senha@123"
      ACCEPT_EULA: "Y"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  # ─── MICROSSERVIÇOS ───────────────────────────────────────

  users-api:
    build:
      context: ../UsersAPI
      dockerfile: Dockerfile
    container_name: users-api
    restart: always
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
      - mongodb
      - rabbitmq
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MS_UserAPI=Server=sqlserver,1433;Database=MS_UsersAPI;User Id=sa;Password=Senha@123;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
      - Jwt__Key=af3b1d967c45e0df2b84ca91fe3a9d6f1148e2c0e9b7d04a51f396cb8f0a7d32
      - Jwt__Issuer=UserAPI
      - Jwt__Audience=https://api.UserAPI.com
      - Serilog__WriteTo__0__Args__databaseUrl=mongodb://root:root@mongodb:27017/logs_dev?authSource=admin

  catalog-api:
    build:
      context: ../CatalogAPI
      dockerfile: Dockerfile
    container_name: catalog-api
    restart: always
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver
      - mongodb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MS_CatalogAPI=Server=sqlserver,1433;Database=MS_CatalogAPI;User Id=sa;Password=Senha@123;TrustServerCertificate=True
      - MongoDB__ConnectionString=mongodb://root:root@mongodb:27017/?authSource=admin
      - MongoDB__DatabaseName=MS_CatalogAPI
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
      - Jwt__Key=af3b1d967c45e0df2b84ca91fe3a9d6f1148e2c0e9b7d04a51f396cb8f0a7d32
      - Jwt__Issuer=UserAPI
      - Jwt__Audience=https://api.UserAPI.com
      - Serilog__WriteTo__0__Args__databaseUrl=mongodb://root:root@mongodb:27017/logs_dev?authSource=admin

  payments-api:
    build:
      context: ../PaymentsAPI
      dockerfile: Dockerfile
    container_name: payments-api
    restart: always
    ports:
      - "5003:8080"
    depends_on:
      - sqlserver
      - mongodb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MS_PaymentAPI=Server=sqlserver,1433;Database=MS_PaymentAPI;User Id=sa;Password=Senha@123;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
      - Serilog__WriteTo__0__Args__databaseUrl=mongodb://root:root@mongodb:27017/logs_dev?authSource=admin

  # ─── API GATEWAY ─────────────────────────────────────────

  kong:
    image: kong:3.6
    container_name: kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_DNS_RESOLVER: "127.0.0.11"
    dns:
      - 127.0.0.11
    dns_opt:
     - ndots:0
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./kong/kong.yaml:/kong/declarative/kong.yaml:ro
    depends_on:
      - users-api
      - catalog-api

  # ─── OBSERVABILIDADE ──────────────────────────────────────

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro

  localstack:
    image: localstack/localstack:3.8.1
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      SERVICES: lambda,logs,iam,s3
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      LAMBDA_DOCKER_NETWORK: orchestrationapi_default
      DEBUG: "1"
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack-data: