apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'users-api'
        static_configs:
          - targets: ['users-api-service:80']
        metrics_path: '/metrics'

      - job_name: 'catalog-api'
        static_configs:
          - targets: ['catalog-api-service:80']
        metrics_path: '/metrics'
